site_name: Ruia
site_url: https://howie6879.github.io/ruia/
site_description: An async web scraping micro-framework based on asyncio.
site_author: howie.hu

repo_url: https://github.com/howie6879/ruia
repo_name: 'howie6879/ruia'

copyright: Copyright &copy; 2018 - 2019 <a href="https://github.com/howie6879/ruia">howie.hu</a>.

theme:
  name: 'material'

pages:
- Introduction: index.md
- Tutorials: ./en/tutorials.md
- Plugins: ./en/plugins.md
- Topics:
  - Item: ./en/topics/item.md
  - Selector: ./en/topics/selector.md
  - Request: ./en/topics/request.md
  - Response: ./en/topics/response.md
  - Middleware: ./en/topics/middleware.md
  - Spider: ./en/topics/spider.md

plugins:
- search

markdown_extensions:
- toc:
    permalink: []
- admonition
- def_list
- codehilite