site_name: Ruia
site_url: https://howie6879.github.io/ruia/
site_description: An async web scraping micro-framework based on asyncio.
site_author: howie.hu

repo_url: https://github.com/howie6879/ruia
repo_name: 'howie6879/ruia'

copyright: Copyright &copy; 2018 - 2019 <a href="https://github.com/howie6879/ruia">howie.hu</a>.

theme:
  name: 'material'

use_directory_urls: false

nav:
  - Introduction: index.md
  - Tutorials:
      - Overview: ./en/tutorials/overview.md
      - Installation: ./en/tutorials/installation.md
      - Field: ./en/tutorials/field.md
      - Item: ./en/tutorials/item.md
      - Spider: ./en/tutorials/spider.md
      - Request: ./en/tutorials/request.md
      - Response: ./en/tutorials/response.md
      - Middleware: ./en/tutorials/middleware.md
      - Plugins: ./en/tutorials/plugins.md
  - Plugins: ./en/plugins.md
  - APIs:
      - Item: ./en/apis/item.md
      - Field: ./en/apis/field.md
      - Request: ./en/apis/request.md
      - Response: ./en/apis/response.md
      - Middleware: ./en/apis/middleware.md
      - Spider: ./en/apis/spider.md
  - Examples:
      - Quick Start: ./en/examples/quick-start.md
      - Typical spider: ./en/examples/typical.md
      - Full featured project: ./en/examples/project.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: []
  - admonition
  - def_list
  - codehilite